version: '3.6' 

services:  
  app:
    image: beatnick/rubotnik:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis:alpine
    container_name: "redis"