version: '3.6' 

services:  
  app:
    build:
      context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "6739:6739"
    ##Development##
    #stdin_open: true
    #tty: true
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6379:6379"