version: '3.6' 

services:  
  app:
    image: beatnick/rubotnik:latest
    # build:
    #   context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "6739:6739"
  redis:
    image: redis:alpine
    container_name: "redis"
    ports:
      - "6379:6379"