version: '3.6' 

services:  
    app:
        build:
            context: ./
        stdin_open: true
        tty: true
        environment: 
            - TOKEN=ENTER_TOKEN_HERE
    redis:
        volumes: 
            - ./rubotnik/data:/data